GET http://localhost:8000/api/user 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvcmVnaXN0ZXIiLCJpYXQiOjE3MjQ4NjUyNTYsImV4cCI6MTcyNDg2ODg1NiwibmJmIjoxNzI0ODY1MjU2LCJqdGkiOiJqdnpyS2M1U3lYVVI3M2YxIiwic3ViIjoiMiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.8x24CPzhI5pqc60a49L5fmpR0Q-G5nb1BLjmF4Occbk
Content-Type: application/json